version: '3'

services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3307:3306"



volumes:
  database:
